[package]
name = "opal-cli"
description = "The opal command-line interface."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
opal-core.workspace = true
clap.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "opal"
path = "src/main.rs"
