// Generated by base/tools/build-terminal-demo.py from a terminal capture of
// the six commands the demo plays. Every line is what opal printed; the
// warnings after each result are left out, and the first install shows its
// resolving count and then its result, not the download in between.
window.OPAL_DEMO = {
 "install": {
  "header": "<span class=\"t-b\">opal install</span> <span class=\"t-d\">v0.4.0 (d036770)</span>",
  "frames": [
   {
    "html": "<span class=\"t-sky\">⠹</span> <span class=\"t-b\">resolving</span>  <span class=\"t-d\">0s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠋</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [11/11]</span>  <span class=\"t-d\">1s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠇</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [75/75]</span>  <span class=\"t-d\">3s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠸</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [87/204]</span>  <span class=\"t-d\">4s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠋</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [399/415]</span>  <span class=\"t-d\">5s</span>",
    "ms": 240
   }
  ],
  "result": [
   "<span class=\"t-g\">+</span> <span class=\"t-b\">next</span><span class=\"t-d\">@16.3.2</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">react</span><span class=\"t-d\">@19.2.8</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">react-dom</span><span class=\"t-d\">@19.2.8</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">@tailwindcss/postcss</span><span class=\"t-d\">@4.3.3</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">@types/node</span><span class=\"t-d\">@20.19.43</span> <span class=\"t-d\">(+ 6 more)</span>",
   "<span class=\"t-g\">364</span> packages installed <span class=\"t-d\">[</span><span class=\"t-b\">26.0s</span><span class=\"t-d\">]</span>  <span class=\"t-d\">(resolve 5.8s, fetch 19.2s, link 836ms)</span>",
   "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
  ]
 },
 "again": [
  "<span class=\"t-b\">opal install</span> <span class=\"t-d\">v0.4.0 (d036770)</span>",
  "<span class=\"t-g\">364</span> packages already installed <span class=\"t-d\">[</span><span class=\"t-b\">458ms</span><span class=\"t-d\">]</span>",
  "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
 ],
 "add": [
  "<span class=\"t-b\">opal add</span> <span class=\"t-d\">v0.4.0 (d036770)</span>",
  "<span class=\"t-g\">+</span> <span class=\"t-b\">zustand</span><span class=\"t-d\">@5.0.15</span>",
  "<span class=\"t-g\">365</span> packages installed <span class=\"t-d\">[</span><span class=\"t-b\">589ms</span><span class=\"t-d\">]</span>  <span class=\"t-d\">(resolve 457ms, fetch 73ms, link 33ms)</span>",
  "<span class=\"t-d\">1 added, 364 already in place</span>",
  "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
 ],
 "frozen": [
  "<span class=\"t-b\">opal install</span> <span class=\"t-d\">v0.4.0 (d036770)</span>",
  "<span class=\"t-g\">365</span> packages already installed <span class=\"t-d\">[</span><span class=\"t-b\">449ms</span><span class=\"t-d\">]</span>",
  "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
 ],
 "verify": [
  "18533 objects, 517.9 MiB",
  "temp files: 0",
  "all objects match their hash keys"
 ],
 "upgrade": [
  "opal 0.4.0 is already the latest release"
 ]
};
