// Generated by base/tools/build-terminal-demo.py from a terminal capture of
// the five commands the demo plays. Every line is what opal printed; the
// warnings after each result are left out, and the first install shows its
// resolving count and then its result, not the download in between.
window.OPAL_DEMO = {
 "install": {
  "header": "<span class=\"t-b\">opal install</span> <span class=\"t-d\">v0.3.1 (10d96c0)</span>",
  "frames": [
   {
    "html": "<span class=\"t-sky\">⠋</span> <span class=\"t-b\">resolving</span>  <span class=\"t-d\">0s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠦</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [11/11]</span>  <span class=\"t-d\">1s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠹</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [75/75]</span>  <span class=\"t-d\">2s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠙</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [209/209]</span>  <span class=\"t-d\">4s</span>",
    "ms": 240
   },
   {
    "html": "<span class=\"t-sky\">⠦</span> <span class=\"t-b\">resolving</span><span class=\"t-d\">  [399/415]</span>  <span class=\"t-d\">5s</span>",
    "ms": 240
   }
  ],
  "result": [
   "<span class=\"t-g\">+</span> <span class=\"t-b\">next</span><span class=\"t-d\">@16.3.2</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">react</span><span class=\"t-d\">@19.2.8</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">react-dom</span><span class=\"t-d\">@19.2.8</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">@tailwindcss/postcss</span><span class=\"t-d\">@4.3.3</span>",
   "<span class=\"t-g\">+</span> <span class=\"t-b\">@types/node</span><span class=\"t-d\">@20.19.43</span> <span class=\"t-d\">(+ 6 more)</span>",
   "<span class=\"t-g\">364</span> packages installed <span class=\"t-d\">[</span><span class=\"t-b\">31.3s</span><span class=\"t-d\">]</span>  <span class=\"t-d\">(resolve 5.5s, fetch 24.7s, link 1.0s)</span>",
   "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
  ]
 },
 "again": [
  "<span class=\"t-b\">opal install</span> <span class=\"t-d\">v0.3.1 (10d96c0)</span>",
  "<span class=\"t-g\">364</span> packages already installed <span class=\"t-d\">[</span><span class=\"t-b\">486ms</span><span class=\"t-d\">]</span>",
  "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
 ],
 "frozen": [
  "<span class=\"t-b\">opal install</span> <span class=\"t-d\">v0.3.1 (10d96c0)</span>",
  "<span class=\"t-g\">364</span> packages already installed <span class=\"t-d\">[</span><span class=\"t-b\">570ms</span><span class=\"t-d\">]</span>",
  "<span class=\"t-d\">skipped 66 optional packages built for other platforms</span>"
 ],
 "verify": [
  "18487 objects, 517.5 MiB",
  "temp files: 0",
  "all objects match their hash keys"
 ],
 "upgrade": [
  "opal 0.3.1 is already the latest release"
 ]
};
